package akka.persistence.snapshot.sqlasync

import akka.persistence.helper.PostgreSQLInitializer
import akka.persistence.snapshot.SnapshotStoreSpec

class PostgreSQLSnapshotStoreSpec extends SnapshotStoreSpec with PostgreSQLInitializer
